"""add model pricing and project custom pricing

Revision ID: 24c8c3f89b4f
Revises: f5ba9156594b
Create Date: 2026-08-24 14:46:01.991599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c8c3f89b4f'
down_revision: Union[str, Sequence[str], None] = 'f5ba9156594b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('output_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricing_model'), 'model_pricing', ['model'], unique=True)
    op.add_column('projects', sa.Column('custom_pricing', sa.JSON(), nullable=True))
    # Seed global pricing from the former hardcoded MODEL_PRICING
    model_pricing = sa.table(
        'model_pricing',
        sa.column('model', sa.String),
        sa.column('input_price', sa.Numeric),
        sa.column('output_price', sa.Numeric),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    import datetime
    now = datetime.datetime.utcnow()
    seed = [
        ("gpt-4o", 2.50, 10.00),
        ("gpt-4o-mini", 0.15, 0.60),
        ("gpt-4.1", 2.00, 8.00),
        ("gpt-4.1-mini", 0.40, 1.60),
        ("gpt-3.5-turbo", 0.50, 1.50),
        ("claude-3-5-sonnet-20241022", 3.00, 15.00),
        ("claude-3-5-haiku-20241022", 0.80, 4.00),
        ("grok-4.6", 2.00, 6.00),
        ("grok-4.5", 2.00, 6.00),
        ("grok-4.3", 1.25, 2.50),
        ("grok-4.20-0309-reasoning", 1.25, 2.50),
        ("grok-4.20-0309-non-reasoning", 1.25, 2.50),
        ("grok-build-0.1", 1.00, 2.00),
        ("openai/gpt-oss-120b", 0.15, 0.60),
        ("openai/gpt-oss-20b", 0.075, 0.30),
    ]
    op.bulk_insert(model_pricing, [
        {"model": m, "input_price": i, "output_price": o, "is_active": True, "created_at": now, "updated_at": now}
        for m, i, o in seed
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'custom_pricing')
    op.drop_index(op.f('ix_model_pricing_model'), table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
